spring:
  application:
    name: config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liudaze/spring-cloud-learning.git
          search-paths:
          - config-repo-demo
server:
  port: 1301

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/